server:
  port: 19091

spring:
  application:
    name: gateway-server

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
        - id: queue
          uri: lb://QUEUE
          predicates:
            - Path=/api/queues, /api/queues/**
        - id: reservation
          uri: lb://RESERVATION
          predicates:
            - Path=/api/reservations, /api/reservations/**
        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/api/stores/{storeId}/reviews/**, /api/stores/{storeId}/reservations/{reservationId}/reviews/**
        - id: store
          uri: lb://STORE
          predicates:
            - Path=/api/stores/**
        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROD_URL}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway=DEBUG:

jwt:
  secret:
    key: ${JWT_SECRET_KEY}