server:
  port: 19091

spring:
  application:
    name: gateway-server

  main:
    web-application-type: reactive
  data:
    redis:
      host: ${REDIS_HOST}

      port: ${REDIS_PORT}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://3.137.169.105:19092
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
        - id: queue-service
          uri: http://3.135.209.115:19096
          predicates:
            - Path=/api/queues, /api/queues/**
        - id: reservation-service
          uri: http://3.139.88.124:19094
          predicates:
            - Path=/api/reservations, /api/reservations/**
        - id: review-service
          uri: http://3.135.206.14:19097
          predicates:
            - Path=/api/stores/{storeId}/reviews/**, /api/stores/{storeId}/reservations/{reservationId}/reviews/**
        - id: store-service
          uri: http://3.144.16.75:19093
          predicates:
            - Path=/api/stores/**
        - id: payment-service
          uri: http://3.138.203.18:19095
          predicates:
            - Path=/api/payments/**



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROD_URL}
  instance:
    prefer-ip-address: true
    ip-address: 18.217.92.13
    hostname: 18.217.92.13

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}