server:
  port: 19091

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

