server:
  port: 19092

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
      open-in-view: false

---
spring:
  application:
    name: user-servic
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_LOCAL_USERNAME}
    password: ${SPRING_DATASOURCE_LOCAL_PASSWORD}
    url: ${SPRING_DATASOURCE_LOCAL_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}