services:

  gateway:
    image: laira2/quit:gateway-server-latest
    container_name: gateway
    build:
      context: .
      dockerfile: gateway-server/Dockerfile
      args:
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        EUREKA_PROD_URL: ${EUREKA_PROD_URL}
        FILE_DIRECTORY: ./gateway-server
        SERVICE: "gateway"
    ports:
      - "19091:8080"  # 외부:내부
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      - eureka

  eureka:
    image: laira2/quit:eureka-server-latest
    container_name: eureka
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
      args:
        EUREKA_PROD_URL: ${EUREKA_PROD_URL}
        FILE_DIRECTORY: ./eureka-server
        SERVICE: "eureka"
    ports:
      - "19090:8761"  # Eureka 서버는 표준 포트 유지
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env

