services:
  gateway-server:
    image: laira2/quit:gateway-server-latest
    container_name: gateway-server # 외부:내부
    environment:
      - EUREKA_PROD_URL=${EUREKA_PROD_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "19091:19091"
