services:
  gateway:
    image: laira2/quit:gateway-server-latest
    container_name: gateway
    ports:
      - "19091:8080"  # 외부:내부
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
