services:
  gateway-server:
    image: laira2/quit:gateway-server-latest
    container_name: gateway-server
    ports:
      - "19091:19091"  # 외부:내부
    build:
      context: .
      dockerfile: gateway-server/Dockerfile
      args:
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        EUREKA_PROD_URL: ${EUREKA_PROD_URL}
        FILE_DIRECTORY: ./gateway-server
    networks:
      - gateway-network
networks:
  gateway-network:
    driver: bridge