services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - quit-payment-network

  payment-service:
    image: laira2/quit:payment-latest
    container_name: payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_PROD_URL=${EUREKA_PROD_URL}
      - DATASOURCE_DRIVER_CLASS_NAME=${DATASOURCE_DRIVER_CLASS_NAME}
      - DATASOURCE_PROD_USERNAME=${DATASOURCE_PROD_USERNAME}
      - DATASOURCE_PROD_PASSWORD=${DATASOURCE_PROD_PASSWORD}
      - PAYMENT_DATASOURCE_PROD_URL=${PAYMENT_DATASOURCE_PROD_URL}
      - PAYMENT_SECRET_KEY=${PAYMENT_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_SERVER=${KAFKA_SERVER}
#      - RESERVATION_BASE_URL=${RESERVATION_BASE_URL}
    ports:
      - "19095:19095"
    depends_on:
      - redis
    networks:
      - quit-payment-network

networks:
  quit-payment-network:
    driver: bridge