services:
  user:
    image: laira2/quit:user-latest
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_PROD_URL=${EUREKA_PROD_URL}
      - DATASOURCE_DRIVER_CLASS_NAME=${DATASOURCE_DRIVER_CLASS_NAME}
      - DATASOURCE_PROD_USERNAME=${DATASOURCE_PROD_USERNAME}
      - DATASOURCE_PROD_PASSWORD=${DATASOURCE_PROD_PASSWORD}
      - USER_DATASOURCE_PROD_URL=${USER_DATASOURCE_PROD_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
