###회원 가입
POST http://host.docker.internal:19091/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "email":"user6@email.com",
  "password" :"User6666@",
  "nickname":"사용자6",
  "phone":"010-6666-6666",
  "birthdate":"2000-06-06"
}

###로그인
POST http://host.docker.internal:19091/api/auth/login
Content-Type: application/json
Accept: application/json

{
"email":"user5@email.com",
"password" :"User5555@"
}

###사용자 전체 조회
GET http://host.docker.internal:19091/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMDIiLCJlbWFpbCI6InVzZXI1QGVtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwibmlja25hbWUiOiLsgqzsmqnsnpA1IiwiaWF0IjoxNzM2MzkyNTY2LCJleHAiOjE3MzYzOTYxNjZ9.zjmQ3TzKUPDf2SPGK-svh8Z_eSQ-Z991-Gfd_7gh07k

###특정 사용자 조회
GET http://host.docker.internal:19091/api/users/302
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMDIiLCJlbWFpbCI6InVzZXI1QGVtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwibmlja25hbWUiOiLsgqzsmqnsnpA1IiwiaWF0IjoxNzM2Mzk0MTM1LCJleHAiOjE3MzYzOTc3MzV9.o0w2hwZbEP1_PEKy5NvwSjHYP56_-xUWykjQvEhztF0

###회원 정보 수정
PUT http://host.docker.internal:19091/api/users/1
Content-Type: application/json
Accept: application/json

{
  "email":"user1@email.com",
  "nickname":"갈매기살항정살",
  "phone":"010-1111-4444",
  "birthdate":"2000-05-05"
}

###사용자 탈퇴
DELETE http://host.docker.internal:19091/api/users/152
Content-Type: application/json
Accept: application/json