spring:
  application:
    name: queue
  profiles:
    active: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  main:
    web-application-type: reactive
server:
  port: 19096

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROD_URL}

store:
  baseUrl: ${STORE_BASEURL}

gateway:
  baseUrl: ${GATEWAY_BASEURL}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG