spring:
  application:
    name: queue
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG