spring:
  application:
    name: notification
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
server:
  port: 19098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
slack:
  token: ${SLACK_TOKEN}