spring:
  application:
    name: payment-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    username: ${DATASOURCE_PROD_USERNAME}
    password: ${DATASOURCE_PROD_PASSWORD}
    url: ${PAYMENT_DATASOURCE_PROD_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_PROD_URL}

payment:
  secret-key: ${PAYMENT_SECRET_KEY}
  base-url: https://api.tosspayments.com/v1/payments

logging:
  level:
    root: INFO
    com.quit.payment.infrastructure: DEBUG
    feign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus