spring:
  application:
    name: payment
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

payment:
  secret-key: ${PAYMENT_SECRET_KEY}
  base-url: https://api.tosspayments.com/v1/payments

logging:
  level:
    root: INFO
    com.quit.payment.infrastructure: DEBUG
    feign: DEBUG