eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_PROD_URL}
  instance:
    hostname: ${EUREKA_EC2_HOST}  # EC2 퍼블릭 IP
    prefer-ip-address: true
    non-secure-port: 8761         # 컨테이너 내부 포트
    non-secure-port-enabled: true