spring:
  application:
    name: server
  profiles:
    active: dev

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost