server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_PROD_URL}
  instance:
    hostname: ${EUREKA_EC2_HOST}
    prefer-ip-address: true
    non-secure-port-enabled: true
    non-secure-port: 19090