name: Quit CI

on:
  push:
    branches:
      - feat/112-quit

jobs:
  build-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 도커 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: eureka 빌드
        run: |
          cd eureka-server
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========eureka========="
          cd ../

      - name: eureka 도커 이미지 빌드 & push
        run: |
          docker compose -f eureka-server-compose.yml build --no-cache
          docker push "laira2/quit:eureka-server-latest"
        env:
          EUREKA_PROD_URL: ${{ secrets.EUREKA_PROD_URL }}

      - name: gateway 빌드
        run: |
          cd gateway-server
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========gateway========="
          cd ../

      - name: gateway 도커 이미지 빌드 & push
        run: |
          docker compose -f gateway-server-compose.yml build --no-cache
          docker push "laira2/quit:gateway-server-latest"
        env:
          EUREKA_PROD_URL: ${{ secrets.EUREKA_PROD_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: user 빌드
        run: |
          cd user
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========user========="
          ls build/libs
          cd ../

      - name: store 빌드
        run: |
          cd store
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========store========="
          ls build/libs
          cd ../

      - name: payment 빌드
        run: |
          cd payment
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========payment========="
          ls build/libs
          cd ../

      - name: queue 빌드
        run: |
          cd queue
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========queue========="
          ls build/libs
          cd ../

      - name: queue 도커 이미지 빌드 & push
        run: |
          docker compose -f queue-compose.yml build --no-cache
          docker push "laira2/quit:queue-latest"
        env:
          EUREKA_PROD_URL: ${EUREKA_PROD_URL}
          REDIS_HOST: ${REDIS_HOST}
          REDIS_PORT: ${REDIS_PORT}
          REDIS_USERNAME: ${REDIS_USERNAME}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          STORE_BASEURL: ${STORE_BASEURL}
          GATEWAY_BASEURL: ${GATEWAY_BASEURL}

      - name: reservation 빌드
        run: |
          cd reservation
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========reservation========="
          ls build/libs
          cd ../

      - name: review 빌드
        run: |
          cd review
          chmod +x gradlew
          ./gradlew clean build -x test --no-daemon -Dspring.profiles.active=prod
          echo "========review========="
          ls build/libs
          cd ../

      - name: Build, Tag and Push docker image to Hub
        run: |
          docker compose -f prometheus-compose.yml build
          docker compose -f reservation-compose.yml build
          docker compose -f payment-compose.yml build
          docker compose build
          docker push "laira2/quit:user-latest"
          docker push "laira2/quit:store-latest"
          docker push "laira2/quit:reservation-latest"
          docker push "laira2/quit:payment-latest"
          docker push "laira2/quit:review-latest"
        env:
          DOCKER_HUB_REPOSITORY: "quit"
          EUREKA_PROD_URL: ${{ secrets.EUREKA_PROD_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          PAYMENT_SECRET_KEY: ${{ secrets.PAYMENT_SECRET_KEY }}
          DATASOURCE_DRIVER_CLASS_NAME: ${{ secrets.DATASOURCE_DRIVER_CLASS_NAME }}
          DATASOURCE_PROD_USERNAME: ${{ secrets.DATASOURCE_PROD_USERNAME }}
          DATASOURCE_PROD_PASSWORD: ${{ secrets.DATASOURCE_PROD_PASSWORD }}
          PAYMENT_DATASOURCE_PROD_URL: ${{ secrets.PAYMENT_DATASOURCE_PROD_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          STORE_BASEURL: ${{ secrets.STORE_BASEURL }}
          GATEWAY_BASEURL: ${{ secrets.GATEWAY_BASEURL }}
          RESERVATION_DATASOURCE_PROD_URL: ${{ secrets.RESERVATION_DATASOURCE_PROD_URL }}
          STORE_DATASOURCE_PROD_URL: ${{ secrets.STORE_DATASOURCE_PROD_URL }}
          USER_DATASOURCE_PROD_URL: ${{ secrets.USER_DATASOURCE_PROD_URL }}
          REVIEW_DATASOURCE_PROD_URL: ${{ secrets.REVIEW_DATASOURCE_PROD_URL }}
          RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
          RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

  deploy:
    needs:
      - build-services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: AWS 인증 정보 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 도커 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v4
      - name: docker-compose 복제
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu"

      - name: eureka-server-compose.yml 복제
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EUREKA_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "eureka-server-compose.yml"
          target: "/home/ubuntu"

      - name: Gateway-server-compose.yml 복제
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GATEWAY_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "gateway-server-compose.yml"
          target: "/home/ubuntu"

      - name: prometheus.yml 복제
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROMETHEUS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "prometheus.yml"
          target: "/home/ubuntu"

      - name: prometheus-compose.yml 복제
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROMETHEUS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "prometheus-compose.yml"
          target: "/home/ubuntu"

      - name: queue-compose.yml 복제
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.QUEUE_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "prometheus-compose.yml"
          target: "/home/ubuntu"

      - name: Add environment variables to Parameter Store
        run: |
          declare -A params
          params["EUREKA_PROD_URL"]="${{ secrets.EUREKA_PROD_URL }}"
          params["JWT_SECRET_KEY"]="${{ secrets.JWT_SECRET_KEY }}"
          params["PAYMENT_SECRET_KEY"]="${{ secrets.PAYMENT_SECRET_KEY }}"
          params["DATASOURCE_DRIVER_CLASS_NAME"]="${{ secrets.DATASOURCE_DRIVER_CLASS_NAME }}"
          params["DATASOURCE_PROD_USERNAME"]="${{ secrets.DATASOURCE_PROD_USERNAME }}"
          params["DATASOURCE_PROD_PASSWORD"]="${{ secrets.DATASOURCE_PROD_PASSWORD }}"
          params["PAYMENT_DATASOURCE_PROD_URL"]="${{ secrets.PAYMENT_DATASOURCE_PROD_URL }}"
          params["REDIS_HOST"]="${{ secrets.REDIS_HOST }}"
          params["REDIS_PORT"]="${{ secrets.REDIS_PORT }}"
          params["REDIS_USERNAME"]="${{ secrets.REDIS_USERNAME }}"
          params["REDIS_PASSWORD"]="${{ secrets.REDIS_PASSWORD }}"
          params["STORE_BASEURL"]="${{ secrets.STORE_BASEURL }}"
          params["GATEWAY_BASEURL"]="${{ secrets.GATEWAY_BASEURL }}"
          params["RESERVATION_DATASOURCE_PROD_URL"]="${{ secrets.RESERVATION_DATASOURCE_PROD_URL }}"
          params["STORE_DATASOURCE_PROD_URL"]="${{ secrets.STORE_DATASOURCE_PROD_URL }}"
          params["USER_DATASOURCE_PROD_URL"]="${{ secrets.USER_DATASOURCE_PROD_URL }}"
          params["REVIEW_DATASOURCE_PROD_URL"]="${{ secrets.REVIEW_DATASOURCE_PROD_URL }}"
          params["RESERVATION_DATASOURCE_PROD_URL"]="${{ secrets.REVIEW_DATASOURCE_PROD_URL }}"
          params["RABBITMQ_HOST"]="${{ secrets.RABBITMQ_HOST }}"
          params["RABBITMQ_PORT"]="${{ secrets.RABBITMQ_PORT }}"
          params["RABBITMQ_USERNAME"]="${{ secrets.RABBITMQ_USERNAME }}"
          params["RABBITMQ_PASSWORD"]="${{ secrets.RABBITMQ_PASSWORD }}"
          params["JWT_SECRET_KEY"]="${{ secrets.JWT_SECRET_KEY }}"
          params["S3_ACCESS_KEY"]="${{ secrets.S3_ACCESS_KEY }}"
          params["S3_SECRET_KEY"]="${{ secrets.S3_SECRET_KEY }}"
          params["S3_BUCKET"]="${{ secrets.S3_BUCKET }}"
          params["FEIGN_URL"]="${{ secrets.FEIGN_URL }}"
          params["PAYMENT_SECRET_KEY"]="${{ secrets.PAYMENT_SECRET_KEY }}"

          # Iterate over the parameters and create them in Parameter Store
          for key in "${!params[@]}"; do
            aws ssm put-parameter \
              --name "/quit/$key" \
              --value "${params[$key]}" \
              --type "SecureString" \
              --overwrite
          done

      - name: Eureka server 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          host: ${{ secrets.EUREKA_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            # AWS SSM에서 파라미터 가져오기
            EUREKA_PROD_URL=$(aws ssm get-parameter --name "/quit/EUREKA_PROD_URL" --with-decryption --query "Parameter.Value" --output text)

            # EUREKA_PROD_URL 환경 변수 export
            export EUREKA_PROD_URL
      
            # Docker Compose 실행
            sudo docker-compose -f /home/ubuntu/eureka-server-compose.yml down --remove-orphans
            sudo docker-compose -f /home/ubuntu/eureka-server-compose.yml pull
      
            # 환경 변수를 설정하고 Docker Compose up
            SPRING_PROFILES_ACTIVE=prod EUREKA_PROD_URL=$EUREKA_PROD_URL sudo docker-compose -f /home/ubuntu/eureka-server-compose.yml up -d

      - name:  gateway server 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          host: ${{ secrets.GATEWAY_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            # AWS SSM에서 파라미터 가져오기
            EUREKA_PROD_URL=$(aws ssm get-parameter --name "/quit/EUREKA_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            JWT_SECRET_KEY=$(aws ssm get-parameter --name "/quit/JWT_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text)

            export EUREKA_PROD_URL
            export JWT_SECRET_KEY
            
            sudo docker-compose -f /home/ubuntu/gateway-server-compose.yml down --remove-orphans
            sudo docker-compose -f /home/ubuntu/gateway-server-compose.yml pull
            
            SPRING_PROFILES_ACTIVE=prod EUREKA_PROD_URL=$EUREKA_PROD_URL JWT_SECRET_KEY=JWT_SECRET_KEY sudo docker-compose -f /home/ubuntu/gateway-server-compose.yml up -d

      - name: Queue 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          host: ${{ secrets.QUEUE_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            EUREKA_PROD_URL=$(aws ssm get-parameter --name "/quit/EUREKA_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            REDIS_HOST=$(aws ssm get-parameter --name "/quit/REDIS_HOST" --with-decryption --query "Parameter.Value" --output text)
            REDIS_PORT=$(aws ssm get-parameter --name "/quit/REDIS_PORT" --with-decryption --query "Parameter.Value" --output text)
            REDIS_USERNAME=$(aws ssm get-parameter --name "/quit/REDIS_USERNAME" --with-decryption --query "Parameter.Value" --output text)
            REDIS_PASSWORD=$(aws ssm get-parameter --name "/quit/REDIS_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
            STORE_BASEURL=$(aws ssm get-parameter --name "/quit/STORE_BASEURL" --with-decryption --query "Parameter.Value" --output text)
            GATEWAY_BASEURL=$(aws ssm get-parameter --name "/quit/GATEWAY_BASEURL" --with-decryption --query "Parameter.Value" --output text)

            export EUREKA_PROD_URL
            export REDIS_HOST
            export REDIS_PORT
            export REDIS_USERNAME
            export REDIS_PASSWORD
            export STORE_BASEURL
            export GATEWAY_BASEURL
            
            sudo docker-compose -f /home/ubuntu/queue-compose.yml down
            sudo docker-compose -f /home/ubuntu/queue-compose.yml pull
            SPRING_PROFILES_ACTIVE=prod sudo docker-compose -f /home/ubuntu/queue-compose.yml up -d

      - name: reservation 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          host: ${{ secrets.RESERVATION_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            EUREKA_PROD_URL=$(aws ssm get-parameter --name "/quit/EUREKA_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            REDIS_HOST=$(aws ssm get-parameter --name "/quit/REDIS_HOST" --with-decryption --query "Parameter.Value" --output text)
            REDIS_PORT=$(aws ssm get-parameter --name "/quit/REDIS_PORT" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_DRIVER_CLASS_NAME=$(aws ssm get-parameter --name "/quit/DATASOURCE_DRIVER_CLASS_NAME" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_PROD_USERNAME=$(aws ssm get-parameter --name "/quit/DATASOURCE_PROD_USERNAME" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_PROD_PASSWORD=$(aws ssm get-parameter --name "/quit/DATASOURCE_PROD_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
            RESERVATION_DATASOURCE_PROD_URL=$(aws ssm get-parameter --name "/quit/RESERVATION_DATASOURCE_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            FEIGN_URL=$(aws ssm get-parameter --name "/quit/FEIGN_URL" --with-decryption --query "Parameter.Value" --output text)

            export EUREKA_PROD_URL
            export REDIS_HOST
            export REDIS_PORT
            export DATASOURCE_DRIVER_CLASS_NAME
            export DATASOURCE_PROD_USERNAME
            export DATASOURCE_PROD_PASSWORD
            export RESERVATION_DATASOURCE_PROD_URL
            export FEIGN_URL
            
            sudo docker-compose -f /home/ubuntu/reservation-compose.yml down
            sudo docker-compose -f /home/ubuntu/reservation-compose.yml pull
            
            SPRING_PROFILES_ACTIVE=prod sudo docker-compose -f /home/ubuntu/reservation-compose.yml up -d

      - name: payment 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          host: ${{ secrets.PAYMENT_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            EUREKA_PROD_URL=$(aws ssm get-parameter --name "/quit/EUREKA_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_DRIVER_CLASS_NAME=$(aws ssm get-parameter --name "/quit/DATASOURCE_DRIVER_CLASS_NAME" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_PROD_USERNAME=$(aws ssm get-parameter --name "/quit/DATASOURCE_PROD_USERNAME" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_PROD_PASSWORD=$(aws ssm get-parameter --name "/quit/DATASOURCE_PROD_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
            PAYMENT_DATASOURCE_PROD_URL=$(aws ssm get-parameter --name "/quit/PAYMENT_DATASOURCE_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            PAYMENT_SECRET_KEY=$(aws ssm get-parameter --name "/quit/PAYMENT_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text)

            export EUREKA_PROD_URL
            export DATASOURCE_DRIVER_CLASS_NAME
            export DATASOURCE_PROD_USERNAME
            export DATASOURCE_PROD_PASSWORD
            export PAYMENT_DATASOURCE_PROD_URL
            export PAYMENT_SECRET_KEY

            sudo docker-compose -f /home/ubuntu/payment-compose.yml down
            sudo docker-compose -f /home/ubuntu/payment-compose.yml pull

            SPRING_PROFILES_ACTIVE=prod sudo docker-compose -f /home/ubuntu/payment-compose.yml up -d

      - name: user, store, review 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DOCKER_HUB_NAMESPACE: ${{ secrets.DOCKER_HUB_NAMESPACE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, DOCKER_HUB_NAMESPACE
          script: |
            EUREKA_PROD_URL=$(aws ssm get-parameter --name "/quit/EUREKA_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            REDIS_HOST=$(aws ssm get-parameter --name "/quit/REDIS_HOST" --with-decryption --query "Parameter.Value" --output text)
            REDIS_PORT=$(aws ssm get-parameter --name "/quit/REDIS_PORT" --with-decryption --query "Parameter.Value" --output text)
            REDIS_USERNAME=$(aws ssm get-parameter --name "/quit/REDIS_USERNAME" --with-decryption --query "Parameter.Value" --output text)
            REDIS_PASSWORD=$(aws ssm get-parameter --name "/quit/REDIS_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_DRIVER_CLASS_NAME=$(aws ssm get-parameter --name "/quit/DATASOURCE_DRIVER_CLASS_NAME" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_PROD_USERNAME=$(aws ssm get-parameter --name "/quit/DATASOURCE_PROD_USERNAME" --with-decryption --query "Parameter.Value" --output text)
            DATASOURCE_PROD_PASSWORD=$(aws ssm get-parameter --name "/quit/DATASOURCE_PROD_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
            
            USER_DATASOURCE_PROD_URL=$(aws ssm get-parameter --name "/quit/USER_DATASOURCE_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            JWT_SECRET_KEY=$(aws ssm get-parameter --name "/quit/JWT_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text)
            
            STORE_DATASOURCE_PROD_URL=$(aws ssm get-parameter --name "/quit/STORE_DATASOURCE_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            
            REVIEW_DATASOURCE_PROD_URL=$(aws ssm get-parameter --name "/quit/REVIEW_DATASOURCE_PROD_URL" --with-decryption --query "Parameter.Value" --output text)
            RABBITMQ_HOST=$(aws ssm get-parameter --name "/quit/RABBITMQ_HOST" --with-decryption --query "Parameter.Value" --output text)
            RABBITMQ_PORT=$(aws ssm get-parameter --name "/quit/RABBITMQ_PORT" --with-decryption --query "Parameter.Value" --output text)
            RABBITMQ_USERNAME=$(aws ssm get-parameter --name "/quit/RABBITMQ_USERNAME" --with-decryption --query "Parameter.Value" --output text)
            RABBITMQ_PASSWORD=$(aws ssm get-parameter --name "/quit/RABBITMQ_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
            S3_ACCESS_KEY=$(aws ssm get-parameter --name "/quit/S3_ACCESS_KEY" --with-decryption --query "Parameter.Value" --output text)
            S3_SECRET_KEY=$(aws ssm get-parameter --name "/quit/S3_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text)
            S3_BUCKET=$(aws ssm get-parameter --name "/quit/S3_BUCKET" --with-decryption --query "Parameter.Value" --output text)
            
            export EUREKA_PROD_URL
            export REDIS_HOST
            export REDIS_PORT
            export REDIS_USERNAME
            export REDIS_PASSWORD
            export DATASOURCE_DRIVER_CLASS_NAME
            export DATASOURCE_PROD_USERNAME
            export DATASOURCE_PROD_PASSWORD
            
            export USER_DATASOURCE_PROD_URL
            export JWT_SECRET_KEY
            
            export STORE_DATASOURCE_PROD_URL
            
            export REVIEW_DATASOURCE_PROD_URL
            export RABBITMQ_HOST
            export RABBITMQ_PORT
            export RABBITMQ_USERNAME
            export RABBITMQ_PASSWORD
            export S3_ACCESS_KEY
            export S3_SECRET_KEY
            export S3_BUCKET
            
            sudo docker-compose down
            sudo docker-compose pull
            
            SPRING_PROFILES_ACTIVE=prod sudo docker-compose up -d

      - name: Prometheus server 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          host: ${{ secrets.PROMETHEUS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
          script: |
            sudo docker-compose -f /home/ubuntu/prometheus-compose.yml down
            sudo docker-compose -f /home/ubuntu/prometheus-compose.yml pull
            
            SPRING_PROFILES_ACTIVE=prod sudo docker-compose -f /home/ubuntu/prometheus-compose.yml up -d
